######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 22 00:07:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += led.h widgetwithbackground.h
SOURCES += led.cpp widgetwithbackground.cpp
